<?php

function cache_tools_cache($function, array $arguments=NULL, $bin='cache', $expire=CACHE_PERMANENT, $reset=FALSE ) {

  if ( is_null($bin) ) {
    $bin = 'cache';
  }

  if ( is_null($expire) ) {
    $expire = CACHE_PERMANENT;
  }

  if ( ! is_callable($function)
    || is_object($function) ) {
    // we know it's callable, so this must be a closure
    throw new InvalidArgumentException('You must pass a string function name (and not a closure) to ' . __FUNCTION__ . '.');
  }

  $key = md5(serialize(array($function,$arguments)));

  if ( $reset ) {
    drupal_static_reset($key);
    cache_clear_all($key, $bin);
  }

  $data = &drupal_static($key);

  if ( ! isset($data) ) {
    if ($cache = cache_get($key)) {
      $data = $cache->data;
    }
    else {
      $data = $function($arguments);
      cache_set($key, $data, $bin, $expire);
    }
  }

  return $data;
}
