<?php

function cache_tools_cache($function, array $arguments=NULL, $bin='cache', $expire=CACHE_PERMANENT, $reset=FALSE ) {

  if ( ! is_callable($function) ) {
    throw new Exception('You must pass a function name to ' . __FUNCTION__ . '.');
  }

  if ( is_object($function) ) {
  // we know it's callable, so this must be a closure
    throw new Exception('You must pass a function name, not a closure, to ' . __FUNCTION__ . '.');
  }

  $key = md5(serialize(array($function,$arguments)));

  if ( $reset ) {
    drupal_static_reset($key);
    cache_clear_all($key, $bin);
  }

  $data = &drupal_static($key);

  if ( ! isset($data) ) {
    if ($cache = cache_get($key)) {
      $data = $cache->data;
    }
    else {
      $data = $function($arguments);
      cache_set($key, $data, $bin, $expire);
    }
  }

  return $data;
}
